config/routes.rb
TodoLibri::Application.routes.draw do
  resources :settori

  resources :libri

  
  root :to => 'libri#index'
end

app/models/libro.rb
class Libro < ActiveRecord::Base
  belongs_to :settore
  
  mount_uploader :image, ImageUploader
  
  def settore_nome=(nome)
    self.settore = Settore.find_by_nome(nome)
  end

end
  
  

app/models/settore.rb
class Settore < ActiveRecord::Base
  has_many :libri
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/libri_controller.rb
class LibriController < ApplicationController

  respond_to :html, :js, :json 
  
  def index
    @libri = Libro.order("id")
    respond_with @libri
  end


  def show
    @libro = Libro.find(params[:id])
  end

  def new
    @libro = Libro.new
  end

  def edit
    @libro = Libro.find(params[:id])
  end

  def create
    @libro = Libro.new(params.except(:controller, :action))
    @libro.save
  end

  def update
    #raise params[:libro].inspect
    
    @libro = Libro.find(params[:id])
    @libro.update_attributes(params.except(:controller, :action))
    respond_with @libro
  end

  def destroy
    @libro = Libro.find(params[:id])
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libri_url }
      format.json { head :ok }
    end
  end
end

app/controllers/settori_controller.rb
class SettoriController < ApplicationController
  # GET /settori
  # GET /settori.json
  def index
    @settori = Settore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settori }
    end
  end

  # GET /settori/1
  # GET /settori/1.json
  def show
    @settore = Settore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @settore }
    end
  end

  # GET /settori/new
  # GET /settori/new.json
  def new
    @settore = Settore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @settore }
    end
  end

  # GET /settori/1/edit
  def edit
    @settore = Settore.find(params[:id])
  end

  # POST /settori
  # POST /settori.json
  def create
    @settore = Settore.new(params[:settore])

    respond_to do |format|
      if @settore.save
        format.html { redirect_to @settore, notice: 'Settore was successfully created.' }
        format.json { render json: @settore, status: :created, location: @settore }
      else
        format.html { render action: "new" }
        format.json { render json: @settore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settori/1
  # PUT /settori/1.json
  def update
    @settore = Settore.find(params[:id])

    respond_to do |format|
      if @settore.update_attributes(params[:settore])
        format.html { redirect_to @settore, notice: 'Settore was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @settore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settori/1
  # DELETE /settori/1.json
  def destroy
    @settore = Settore.find(params[:id])
    @settore.destroy

    respond_to do |format|
      format.html { redirect_to settori_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libri_helper.rb
module LibriHelper
end

app/helpers/settori_helper.rb
module SettoriHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoLibri</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="header"><h1>Todo-Libri</h1></header>
  <%= yield %>
</body>
</html>

app/views/libri/index.html.erb
<div id="app"></div>

<script type="text/javascript" charset="utf-8">
    
    jQuery(function(){
      new App({el: $("#app")});
    });

</script>

app/views/settori/_form.html.haml
= form_for @settore do |f|
  -if @settore.errors.any?
    #error_explanation
      %h2= "#{pluralize(@settore.errors.count, "error")} prohibited this settore from being saved:"
      %ul
        - @settore.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .actions
    = f.submit 'Save'

app/views/settori/edit.html.haml
%h1 Editing settore

= render 'form'

= link_to 'Show', @settore
\|
= link_to 'Back', settori_path

app/views/settori/index.html.erb
<!-- / %h1 Listing settori
/ 
/ %table
/   %tr
/     %th Nome
/     %th
/     %th
/     %th
/ 
/   - @settori.each do |settore|
/     %tr
/       %td= settore.nome
/       %td= link_to 'Show', settore
/       %td= link_to 'Edit', edit_settore_path(settore)
/       %td= link_to 'Destroy', settore, :confirm => 'Are you sure?', :method => :delete
/ 
/ %br
/ 
/ = link_to 'New Settore', new_settore_path -->

<div id="app"></div>

<script type="text/javascript" charset="utf-8">
    
    jQuery(function(){
      new App({el: $("#app")});
    });

</script>

app/views/settori/index.html.haml
/ %h1 Listing settori
/ 
/ %table
/   %tr
/     %th Nome
/     %th
/     %th
/     %th
/ 
/   - @settori.each do |settore|
/     %tr
/       %td= settore.nome
/       %td= link_to 'Show', settore
/       %td= link_to 'Edit', edit_settore_path(settore)
/       %td= link_to 'Destroy', settore, :confirm => 'Are you sure?', :method => :delete
/ 
/ %br
/ 
/ = link_to 'New Settore', new_settore_path

%div#app

:javascript
  jQuery(function(){
    new App({el: $("#app")});
  });

app/views/settori/new.html.haml
%h1 New settore

= render 'form'

= link_to 'Back', settori_path

app/views/settori/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @settore.nome

= link_to 'Edit', edit_settore_path(@settore)
\|
= link_to 'Back', settori_path